# Generated by Django 5.1.3 on 2025-01-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('one_to_one', 'One to One'), ('group', 'Group'), ('world', 'World')], default='one_to_one', max_length=20),
        ),
    ]
