# Generated by Django 5.1.3 on 2025-01-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_conversation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
