# Generated by Django 5.1.3 on 2025-01-24 14:08

import cloudinary_storage.storage
import inbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_conversation_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=inbox.models.group_profile_path),
        ),
    ]
