# Generated by Django 5.1.3 on 2025-02-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_conversation_users_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmesssage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='inbox_files/'),
        ),
        migrations.AlterField(
            model_name='inboxmesssage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
