# Generated by Django 5.1.3 on 2025-02-08 13:53

import inbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0007_inboxmesssage_file_alter_inboxmesssage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxmesssage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=inbox.models.inbox_file_path),
        ),
    ]
