# Generated by Django 5.1.3 on 2025-02-08 14:33

import cloudinary_storage.storage
import inbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0008_alter_inboxmesssage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxmesssage',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=inbox.models.inbox_file_path),
        ),
    ]
