# Generated by Django 5.1.6 on 2025-03-29 15:26

import cloudinary_storage.storage
import django_resized.forms
import userauths.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='header_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1500, 500], storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=userauths.models.header_image_path),
        ),
    ]
