# Generated by Django 5.1 on 2024-10-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0006_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(null=True, upload_to="profile_picture"),
        ),
    ]
