# Generated by Django 5.1 on 2024-11-01 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0007_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
