# Generated by Django 5.1.3 on 2025-01-04 19:10

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0008_profile_created_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                null=True, upload_to=userauths.models.profile_picture_path
            ),
        ),
    ]
