# Generated by Django 5.1.3 on 2025-01-04 19:14

import cloudinary_storage.storage
import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0009_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=userauths.models.profile_picture_path,
            ),
        ),
    ]
