# Generated by Django 5.0.6 on 2024-08-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_tag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
    ]
