# Generated by Django 5.1 on 2024-10-29 14:04

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_remove_post_likes_likedpost_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.ImageField(
                max_length=5242880,
                null=True,
                upload_to=post.models.user_directory_path,
                verbose_name="Picture",
            ),
        ),
    ]
