# Generated by Django 5.1.3 on 2024-11-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_reportedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportedPost',
        ),
    ]
