# Generated by Django 5.1.3 on 2025-01-04 19:17

import cloudinary_storage.storage
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_reportpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.ImageField(
                max_length=5242880,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=post.models.user_directory_path,
                verbose_name="Picture",
            ),
        ),
    ]
