# Generated by Django 5.1 on 2024-10-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_reply"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
