# Generated by Django 5.1 on 2024-10-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0006_alter_reply_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reply",
            old_name="parent_post",
            new_name="parent_comment",
        ),
    ]
