# Generated by Django 5.1.3 on 2025-02-24 19:38

import cloudinary_storage.storage
import story.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_story_options_rename_user_storyview_viewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=story.models.user_directory_path),
        ),
    ]
