# Generated by Django 5.1 on 2024-08-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_likes"),
        ("userauths", "0002_profile_bio_profile_first_name_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="favourite",
            field=models.ManyToManyField(null=True, to="post.post"),
        ),
    ]
