# Generated by Django 5.1 on 2024-08-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_likes"),
        ("userauths", "0003_alter_profile_favourite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="favourite",
            field=models.ManyToManyField(blank=True, null=True, to="post.post"),
        ),
    ]
