# Generated by Django 5.1 on 2024-10-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_likes"),
        ("userauths", "0004_alter_profile_favourite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="favourite",
            field=models.ManyToManyField(blank=True, to="post.post"),
        ),
    ]
