# Generated by Django 5.1 on 2024-10-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0005_alter_profile_favourite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="avatar_default.png", null=True, upload_to="profile_picture"
            ),
        ),
    ]
